// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccqmbwmqkvjyfipqfzte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcW1id21xa3ZqeWZpcHFmenRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzAzOTQsImV4cCI6MjA2MzE0NjM5NH0.3aQ4FaAFtbjFjSgkH7cZf8t76IymbxCgET3EO8mA5iU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);